# OpenAI API Key
OPENAI_API_KEY = "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"

# File Paths
[paths]
faiss_index = "C:\\Users\\Aqil Anhein\\Desktop\\TA\\app\\pasal.index"
metadata = "C:\\Users\\Aqil Anhein\\Desktop\\TA\\app\\id_mapping.json"
faiss_nama_index = "C:\\Users\\Aqil Anhein\\Desktop\\TA\\app\\nama.index"
metadata_nama = "C:\\Users\\Aqil Anhein\\Desktop\\TA\\app\\id_mapping_nama.json"

# Neo4j Configuration
[neo4j]
uri = "bolt://localhost:7687"
user = "neo4j"
password = "Ghazali12."